### ISSUE TITLE
device limitation on vless+ws

### ISSUE THREAD

**Issue by AltAirGame** [FranzKafkaYu/x-ui#219]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

in the inbound setting device limit not working is it a known issue?

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sarahtuska** [comment]
base on my understanding there is no device limitation per inbound .  I hope they can implemented in . for example  only 50 device per inbound at the same time allowed or just 3 . that would be nice option for us and our servers .

**Comment by sarahtuska** [comment]
the foundation of x-ui i guess . at first they want to everybody connect to internet and bypass blocking . but now because old protocol is garbage and everybody shifting to x-ray i guess is time to add this feature  like u can choose how many device at the same time can connect to one inbound . 
we must wait and see if any of developers able to add that or not . they definitely can add it but we must wait to see if they want to change some of the rules when this protocol being built . im one of the people want that change happens with time . technology has it fast paste and we must adopt.

**Comment by FranzKafkaYu** [comment]
impossible.
