### ISSUE TITLE
xray status "error" when switch to version 1.8.0

### ISSUE THREAD

**Issue by NimaAfshar1993** [FranzKafkaYu/x-ui#344]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

xray status "error" when switch to version 1.8.0 but on 1.7.5 it's ok!

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by FranzKafkaYu** [comment]
@NimaAfshar1993 because xray 1.8.0 doesn't support old XTLS flow:xtls-rprx-direct and xtls-rprx-origin any more.So if you still wanna use the old xtls flow,please don't upgrade to 1.8.0.if you wanna use 1.8.0,please check flow option.and if you use trojan,you should delete these inbounds and create new ones.
