### ISSUE TITLE
求助，为什么甲骨文的vps安装了运行不了

### ISSUE THREAD

**Issue by cn0514** [FranzKafkaYu/x-ui#391]
aws的可以，我自己电脑上的ubuntu也可以运行，但甲骨文的ubuntu20.04却不行，ip：端口 打不开网页

**Comment by FranzKafkaYu** [comment]
> aws的可以，我自己电脑上的ubuntu也可以运行，但甲骨文的ubuntu20.04却不行，ip：端口 打不开网页

请检查防火墙设置。

**Comment by deartonyz** [comment]
> aws 的可以，我自己电脑上的 ubuntu 也可以运行，但甲骨文的 ubuntu20.04 却不行，ip：端口 打不开网页

我是甲骨文,可以正常使用哦.应该是防火墙端口没有放行

**Comment by TaoRone** [comment]
安全组端口没放开

**Comment by cn0514** [comment]
防火墙是关闭的，甲古文进出口是全开的发自我的 iPhone在 2023年5月14日，18:10，Yu FranzKafka ***@***.***> 写道：﻿

aws的可以，我自己电脑上的ubuntu也可以运行，但甲骨文的ubuntu20.04却不行，ip：端口 打不开网页

请检查防火墙设置。

**Comment by cn0514** [comment]
全开了，安装甬哥的x-ui面板可以，删除，再装原版就可以了发自我的 iPhone在 2023年5月14日，19:08，TaoRone ***@***.***> 写道：﻿
安全组端口没放开

**Comment by deartonyz** [comment]
> 全开了，安装甬哥的 x-ui 面板可以，删除，再装原版就可以了发自我的 iPhone 在 2023 年 5 月 14 日，19:08，TaoRone ***@***.***> 写道：﻿ 安全组端口没放开 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

他的那个脚本里面带了开放所有端口的命令

**Comment by cn0514** [comment]
开放所有端口命令是啥？发自我的 iPhone在 2023年5月14日，20:50，WalkArtist ***@***.***> 写道：﻿

全开了，安装甬哥的 x-ui 面板可以，删除，再装原版就可以了发自我的 iPhone 在 2023 年 5 月 14 日，19:08，TaoRone @.> 写道：﻿ 安全组端口没放开 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

他的那个脚本里面带了开放所有端口的命令

**Comment by cn0514** [comment]
sudo ufw status显示Status: inactive也就是防火墙没开吧发自我的 iPhone在 2023年5月14日，20:50，WalkArtist ***@***.***> 写道：﻿

全开了，安装甬哥的 x-ui 面板可以，删除，再装原版就可以了发自我的 iPhone 在 2023 年 5 月 14 日，19:08，TaoRone @.> 写道：﻿ 安全组端口没放开 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

他的那个脚本里面带了开放所有端口的命令

**Comment by deartonyz** [comment]
# 开放指定端口
sudo iptables -I INPUT -p tcp     --dport **** -j ACCEPT
# 查看开放的端口
sudo iptables -nvL
# 关闭指定端口
sudo iptables -I INPUT -p tcp     --dport **** -j DROP
# 保存
iptables-save
# 持久化端口控制
sudo netfilter-persistent     save
sudo netfilter-persistent     reload

发件人: cn0514 ***@***.***>
日期: 星期日, 2023年5月14日 22:40
收件人: FranzKafkaYu/x-ui ***@***.***>
抄送: WalkArtist ***@***.***>, Comment ***@***.***>
主题: Re: [FranzKafkaYu/x-ui] 求助，为什么甲骨文的vps安装了运行不了 (Issue #391)
sudo ufw status显示Status: inactive也就是防火墙没开吧发自我的 iPhone在 2023年5月14日，20:50，WalkArtist ***@***.***> 写道：﻿

全开了，安装甬哥的 x-ui 面板可以，删除，再装原版就可以了发自我的 iPhone 在 2023 年 5 月 14 日，19:08，TaoRone @.> 写道：﻿ 安全组端口没放开 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

他的那个脚本里面带了开放所有端口的命令
